# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "k8s.io/cli-runtime"
  branch = "release-1.14"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.4-2-g300106c228d52c"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.14"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  branch = "master"
  name = "github.com/HouzuoGuo/tiedot"

[[constraint]]
  name = "github.com/RichardKnop/machinery"
  version = "v1.5.5"

[[constraint]]
  branch = "master"
  name = "github.com/fsouza/go-dockerclient"

[[override]]
  branch = "master"
  name = "github.com/hlandau/degoutils"

[[override]]
  branch = "master"
  name = "github.com/docker/docker"

[[override]]
  branch = "master"
  name = "github.com/docker/libnetwork"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/binding"

[[constraint]]
  branch = "master"
  name = "github.com/jaypipes/ghw"

[[constraint]]
  branch = "master"
  name = "github.com/michaelklishin/rabbit-hole"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  branch = "master"
  name = "github.com/mudler/anagent"

[[constraint]]
  name = "github.com/theckman/go-flock"
  version = "0.4.0"

[[constraint]]
  name = "gopkg.in/clog.v1"
  version = "1.1.1"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.3.1"

[[override]]
  name = "github.com/Unknwon/com"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  version = "lxd-3.14"
  name = "github.com/lxc/lxd"

[prune]
  go-tests = true
  unused-packages = true
  #non-go = true

[[prune.project]]
name = "github.com/lxc/lxd"
unused-packages = false
#non-go = false

